default:
  retry:
    max: 2
    when: runner_system_failure
cache:
  key:
    files:
      - package-lock.json
      - docs/package-lock.json
  paths:
    - .npm/
    - docs/.npm

# The Docker image that will be used to build your app
image: node:22-alpine

create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: docs/build
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Functions that should be executed before the build script is run
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cd docs
    - npm ci --cache .npm --prefer-offline
    - npm run generate-typedoc
    - npm run build
